(()=>{
const photoCache=new Map();
function currentLang(){return document.querySelector('.lang button.active')?.textContent?.trim()==='EN'?'en':'ru'}
function pageTitle(){const card=document.querySelector('.card');if(!card)return'';const h=card.querySelector('h2');return h?.textContent?.trim()||''}
async function addPhoto(){const card=document.querySelector('.card');if(!card||card.querySelector('.kando-photo'))return;const title=pageTitle();if(!title)return;const lang=currentLang();const wrap=document.createElement('div');wrap.className='kando-photo kando-photo-loading';wrap.innerHTML='<div class="kando-photo-skeleton"></div>';card.insertBefore(wrap,card.firstChild);
 try{let data=photoCache.get(lang+title);if(!data){const q=encodeURIComponent(title.replace(' и ',' ').replace(' & ',' '));const r=await fetch(`https://${lang}.wikipedia.org/api/rest_v1/page/summary/${q}`);if(r.ok)data=await r.json();if(!data?.thumbnail&&lang!=='en'){const r2=await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${q}`);if(r2.ok)data=await r2.json()}photoCache.set(lang+title,data||{})}
 if(!wrap.isConnected)return;if(data?.thumbnail?.source){wrap.className='kando-photo';wrap.innerHTML=`<img src="${data.thumbnail.source}" alt="${title}" loading="lazy"><a href="${data.content_urls?.desktop?.page||'#'}" target="_blank" rel="noopener">Photo / Wikipedia</a>`}else wrap.remove()
 }catch(e){wrap.remove()}}
function moveRouteMap(){const route=document.querySelector('#ks-route-map');const host=document.querySelector('.mapWrap');if(!route||!host||route.dataset.main==='1')return;route.dataset.main='1';route.classList.add('kando-main-route');host.appendChild(route);host.classList.add('has-ai-route');let badge=host.querySelector('.kando-route-badge');if(!badge){badge=document.createElement('div');badge.className='kando-route-badge';badge.innerHTML='<b>AI ROUTE</b><span>Маршрут построен по вашему запросу</span><button type="button">×</button>';badge.querySelector('button').onclick=()=>{host.classList.remove('has-ai-route');route.remove();badge.remove()};host.appendChild(badge)}setTimeout(()=>window.dispatchEvent(new Event('resize')),100)}
const obs=new MutationObserver(()=>{addPhoto();moveRouteMap()});obs.observe(document.documentElement,{childList:true,subtree:true});addPhoto();moveRouteMap();
})();