(()=>{
const META=[
['tokyo',[3,4,5,10,11],['city','food','culture'],0],['kyoto',[3,4,5,10,11],['culture','food','city'],0],['osaka',[3,4,5,9,10,11],['food','city'],0],['nara',[3,4,5,10,11],['culture','nature'],0],['hakone',[3,4,5,10,11],['onsen','nature','mountains'],0],['kawaguchiko',[3,4,5,10,11],['nature','mountains'],0],['nikko',[4,5,10,11],['culture','nature','mountains'],0],['kamakura',[3,4,5,9,10,11],['sea','culture','nature'],0],['kanazawa',[3,4,5,10,11],['culture','food','city'],0],['takayama',[4,5,10,11],['culture','mountains','food'],0],['shirakawa',[1,2,5,10,11],['culture','mountains','nature'],0],['matsumoto',[4,5,9,10,11],['culture','mountains'],0],['fukui',[4,5,9,10,11],['culture','sea','unusual'],1],['koyasan',[4,5,9,10,11],['culture','mountains','unusual'],1],['kumano',[3,4,5,10,11],['nature','mountains','onsen','unusual'],1],['hiroshima',[3,4,5,10,11],['culture','food','city'],0],['miyajima',[3,4,5,10,11],['culture','nature','sea'],0],['naoshima',[3,4,5,9,10,11],['culture','sea','unusual'],1],['iya',[4,5,10,11],['mountains','nature','unusual'],1],['matsuyama',[3,4,5,10,11],['onsen','culture','city'],1],['beppu',[1,2,3,4,10,11,12],['onsen','unusual'],1],['yufuin',[3,4,5,10,11],['onsen','mountains','food'],1],['aso',[4,5,9,10,11],['nature','mountains','unusual'],1],['kagoshima',[3,4,5,10,11],['food','nature','city'],1],['yakushima',[4,5,10,11],['nature','mountains','unusual'],1],['fukuoka',[3,4,5,10,11],['food','city','sea'],0],['nagasaki',[3,4,5,10,11],['culture','city','sea'],1],['sapporo',[1,2,6,7,8,9],['food','city'],0],['otaru',[1,2,6,7,8,9],['food','sea','culture'],0],['biei',[6,7,8,9],['nature','unusual'],1],['shiretoko',[6,7,8,9,10],['nature','sea','unusual'],1],['aomori',[4,5,8,9,10],['food','culture','sea'],1],['yamadera',[4,5,9,10,11],['culture','mountains','unusual'],1],['ginzan',[1,2,3,10,11,12],['onsen','unusual'],1],['tottori',[3,4,5,9,10,11],['nature','sea','unusual'],1],['ine',[4,5,9,10,11],['sea','culture','unusual'],1],['kiso',[4,5,9,10,11],['culture','nature','unusual'],1],['izumo',[3,4,5,10,11],['culture','sea','unusual'],1],['okayama',[3,4,5,10,11],['culture','city'],1],['nagoya',[3,4,5,10,11],['food','city','culture'],1],['ise',[3,4,5,10,11],['culture','sea','unusual'],1],['amami',[4,5,10,11],['sea','nature','unusual'],1],['okinawa',[3,4,5,10,11],['sea','culture','food'],0]
];
const labels={ru:{all:'Все',culture:'Культура',nature:'Природа',mountains:'Горы',sea:'Море',food:'Еда',onsen:'Онсэн',city:'Города',unusual:'Необычная Япония',placeholder:'Выберите интересы'},en:{all:'All',culture:'Culture',nature:'Nature',mountains:'Mountains',sea:'Sea',food:'Food',onsen:'Onsen',city:'Cities',unusual:'Unusual Japan',placeholder:'Choose interests'}};
const tags=['culture','nature','mountains','sea','food','onsen','city','unusual'];
let selected=new Set(), mounted=false, applying=false;
const lang=()=>document.querySelector('.lang button.active')?.textContent?.trim()==='EN'?'en':'ru';
function currentMeta(){const selects=document.querySelectorAll('.filters select');const month=+(selects[0]?.value||0);const secret=document.querySelector('.filters button.secret')?.classList.contains('on');return META.filter(x=>(!month||x[1].includes(month))&&(!secret||x[3]));}
function apply(){if(applying)return;applying=true;requestAnimationFrame(()=>{const list=currentMeta();const paths=[...document.querySelectorAll('.leaflet-overlay-pane path.leaflet-interactive')];let shown=0;paths.forEach((p,i)=>{const m=list[i];const ok=!m||selected.size===0||m[2].some(t=>selected.has(t));p.style.display=ok?'':'none';p.style.pointerEvents=ok?'':'none';if(ok)shown++;});const count=document.querySelector('.filters .count');const txt=`${shown} places`;if(count&&count.textContent!==txt)count.textContent=txt;updateSummary();applying=false;});}
function updateSummary(){const box=document.querySelector('.multi-interest-summary');if(!box)return;const l=labels[lang()];const txt=selected.size===0?l.all:[...selected].map(t=>l[t]).join(', ');if(box.textContent!==txt)box.textContent=txt;}
function mount(){const filters=document.querySelector('.filters');if(!filters)return;const selects=filters.querySelectorAll('select');if(selects.length<2)return;const original=selects[1];if(document.querySelector('.multi-interest')){apply();return;}original.style.display='none';const label=original.closest('label');const wrap=document.createElement('div');wrap.className='multi-interest';wrap.innerHTML='<button type="button" class="multi-interest-trigger"><span class="multi-interest-summary"></span><span>▾</span></button><div class="multi-interest-menu"></div>';label.appendChild(wrap);const menu=wrap.querySelector('.multi-interest-menu');const render=()=>{const l=labels[lang()];menu.innerHTML=`<label class="mi-option mi-all"><input type="checkbox" data-tag="all" ${selected.size===0?'checked':''}> <span>${l.all}</span></label>`+tags.map(t=>`<label class="mi-option"><input type="checkbox" data-tag="${t}" ${selected.has(t)?'checked':''}> <span>${l[t]}</span></label>`).join('');updateSummary();};render();wrap.querySelector('.multi-interest-trigger').onclick=e=>{e.preventDefault();wrap.classList.toggle('open')};menu.addEventListener('change',e=>{const cb=e.target;if(!(cb instanceof HTMLInputElement))return;const t=cb.dataset.tag;if(t==='all'){selected.clear()}else if(t){cb.checked?selected.add(t):selected.delete(t)}render();apply();});document.addEventListener('click',e=>{if(!wrap.contains(e.target))wrap.classList.remove('open')});
const mo=new MutationObserver(()=>{render();apply()});const langBox=document.querySelector('.lang');if(langBox)mo.observe(langBox,{attributes:true,subtree:true,attributeFilter:['class']});filters.addEventListener('change',()=>setTimeout(apply,0));filters.addEventListener('click',()=>setTimeout(apply,30));mounted=true;apply();}
const observer=new MutationObserver(()=>{mount();if(mounted)apply()});observer.observe(document.body,{childList:true,subtree:true});mount();
})();
