(()=>{const places=[
{id:'tokyo',ru:'Токио',en:'Tokyo',tags:['city','food','culture'],months:[3,4,5,10,11],n:3,area:'east'},
{id:'nikko',ru:'Никко',en:'Nikko',tags:['culture','nature','mountains'],months:[4,5,10,11],n:1,area:'east'},
{id:'kawaguchiko',ru:'Кавагутико',en:'Kawaguchiko',tags:['nature','mountains'],months:[3,4,5,10,11],n:1,area:'east'},
{id:'matsumoto',ru:'Мацумото',en:'Matsumoto',tags:['culture','mountains','small'],months:[4,5,9,10,11],n:1,area:'alps'},
{id:'takayama',ru:'Такаяма',en:'Takayama',tags:['culture','mountains','food','small'],months:[4,5,10,11],n:2,area:'alps'},
{id:'shirakawa',ru:'Сиракава-го',en:'Shirakawa-go',tags:['culture','mountains','nature','small'],months:[1,2,5,10,11],n:1,area:'alps'},
{id:'kanazawa',ru:'Канадзава',en:'Kanazawa',tags:['culture','food','city'],months:[3,4,5,10,11],n:2,area:'alps'},
{id:'fukui',ru:'Фукуи',en:'Fukui',tags:['culture','sea','unusual','small'],months:[4,5,9,10,11],n:1,area:'alps'},
{id:'kyoto',ru:'Киото',en:'Kyoto',tags:['culture','food','city'],months:[3,4,5,10,11],n:2,area:'west'},
{id:'osaka',ru:'Осака',en:'Osaka',tags:['food','city'],months:[3,4,5,9,10,11],n:2,area:'west'},
{id:'koyasan',ru:'Коясан',en:'Koyasan',tags:['culture','mountains','unusual','small'],months:[4,5,9,10,11],n:1,area:'west'},
{id:'kumano',ru:'Кумано-кодо',en:'Kumano Kodo',tags:['nature','mountains','onsen','unusual','small'],months:[3,4,5,10,11],n:2,area:'west'},
{id:'naoshima',ru:'Наосима',en:'Naoshima',tags:['culture','sea','unusual'],months:[3,4,5,9,10,11],n:1,area:'west'},
{id:'hiroshima',ru:'Хиросима',en:'Hiroshima',tags:['culture','food','city'],months:[3,4,5,10,11],n:2,area:'west'},
{id:'miyajima',ru:'Миядзима',en:'Miyajima',tags:['culture','nature','sea'],months:[3,4,5,10,11],n:1,area:'west'},
{id:'fukuoka',ru:'Фукуока',en:'Fukuoka',tags:['food','city','sea'],months:[3,4,5,10,11],n:2,area:'kyushu'},
{id:'beppu',ru:'Бэппу',en:'Beppu',tags:['onsen','unusual'],months:[1,2,3,4,10,11,12],n:1,area:'kyushu'},
{id:'yufuin',ru:'Юфуин',en:'Yufuin',tags:['onsen','mountains','food','small'],months:[3,4,5,10,11],n:1,area:'kyushu'},
{id:'aso',ru:'Асо',en:'Aso',tags:['nature','mountains','unusual'],months:[4,5,9,10,11],n:2,area:'kyushu'},
{id:'kagoshima',ru:'Кагосима',en:'Kagoshima',tags:['food','nature','city','sea'],months:[3,4,5,10,11],n:2,area:'kyushu'},
{id:'yakushima',ru:'Якусима',en:'Yakushima',tags:['nature','mountains','unusual','sea'],months:[4,5,10,11],n:2,area:'kyushu'},
{id:'nagasaki',ru:'Нагасаки',en:'Nagasaki',tags:['culture','city','sea'],months:[3,4,5,10,11],n:2,area:'kyushu'},
{id:'sapporo',ru:'Саппоро',en:'Sapporo',tags:['food','city'],months:[1,2,6,7,8,9],n:2,area:'hokkaido'},
{id:'otaru',ru:'Отару',en:'Otaru',tags:['food','sea','culture','small'],months:[1,2,6,7,8,9],n:1,area:'hokkaido'},
{id:'biei',ru:'Биэй и Фурано',en:'Biei & Furano',tags:['nature','unusual','small'],months:[6,7,8,9],n:2,area:'hokkaido'}];
const legs={
'Tokyo|Matsumoto':['Limited Express Azusa','~2 ч 40 мин','~¥6,600'], 'Matsumoto|Takayama':['Highway bus','~2 ч 30 мин','~¥4,000'], 'Takayama|Shirakawa-go':['Highway bus','~50 мин','~¥2,800'], 'Shirakawa-go|Kanazawa':['Highway bus','~1 ч 15 мин','~¥2,800'], 'Kanazawa|Fukui':['Hokuriku Shinkansen / train','~25–45 мин','~¥3,000–4,000'], 'Kanazawa|Kyoto':['Shinkansen + Limited Express','~2 ч','~¥7,000–8,000'], 'Fukui|Kyoto':['Shinkansen + Limited Express','~1 ч 30 мин','~¥5,000–6,000'], 'Tokyo|Kyoto':['Tokaido Shinkansen','~2 ч 10–40 мин','~¥14,000'], 'Kyoto|Osaka':['JR train','~30 мин','~¥600'], 'Osaka|Koyasan':['Nankai train + cable car','~2 ч','~¥1,700–2,500'], 'Osaka|Hiroshima':['Sanyo Shinkansen','~1 ч 30 мин','~¥11,000'], 'Hiroshima|Miyajima':['JR train + ferry','~45–60 мин','~¥700'], 'Hiroshima|Fukuoka':['Sanyo/Kyushu Shinkansen','~1 ч','~¥9,000'], 'Fukuoka|Beppu':['Limited Express','~2 ч','~¥6,000'], 'Beppu|Yufuin':['Bus / local train','~1 ч','~¥1,000–2,000'], 'Fukuoka|Kagoshima':['Kyushu Shinkansen','~1 ч 20 мин','~¥11,000'], 'Kagoshima|Yakushima':['High-speed ferry / flight','~2–3 ч','~¥12,000–20,000'], 'Tokyo|Kawaguchiko':['Limited Express / highway bus','~2 ч','~¥2,200–4,000'], 'Tokyo|Nikko':['Limited Express / JR','~2 ч','~¥3,000–6,000']};
const months={январ:1,феврал:2,март:3,апрел:4,май:5,июн:6,июл:7,август:8,сентябр:9,октябр:10,ноябр:11,декабр:12,january:1,february:2,march:3,april:4,may:5,june:6,july:7,august:8,september:9,october:10,november:11,december:12};
const tagWords={mountains:['гор','альп','mountain','hiking','трек'],onsen:['онсэн','онсен','onsen','hot spring'],sea:['мор','пляж','остров','sea','beach','ocean'],culture:['культур','храм','истори','culture','temple','history'],food:['еда','гастр','food','ramen'],city:['город','мегапол','city'],unusual:['необыч','мало турист','нетурист','hidden','unusual','off the beaten'],small:['маленьк','деревн','small town','village'],nature:['природ','лес','nature','forest']};
function parse(q){const s=q.toLowerCase();const d=(s.match(/(\d{1,2})\s*(?:дн|день|дней|days?)/)||[])[1];let month=0;Object.entries(months).some(([k,v])=>s.includes(k)&&(month=v,true));const tags=Object.entries(tagWords).filter(([,ws])=>ws.some(w=>s.includes(w))).map(([k])=>k);const tok=(s.match(/токио[^\d]{0,20}(?:максимум|не больше|до)?\s*(\d+)\s*(?:дн|день|дней)/)||s.match(/tokyo[^\d]{0,20}(\d+)\s*days?/));return{days:+d||10,month,tags,tokyoMax:tok?+tok[1]:3,first:/перв(ый|ая).*япон|first.*japan/.test(s),raw:s}}
function recommend(p){let pool=places.map(x=>({...x,score:0}));pool.forEach(x=>{p.tags.forEach(t=>{if(x.tags.includes(t))x.score+=t==='small'?3:2});if(p.month&&x.months.includes(p.month))x.score+=2;if(x.id==='tokyo'&&p.first)x.score+=3;if(x.tags.includes('unusual')&&p.tags.includes('unusual'))x.score+=2});let selected=[];const explicit=places.filter(x=>p.raw.includes(x.ru.toLowerCase())||p.raw.includes(x.en.toLowerCase()));selected.push(...explicit);if(p.first&&!selected.some(x=>x.id==='tokyo'))selected.push(pool.find(x=>x.id==='tokyo'));
const ranked=pool.sort((a,b)=>b.score-a.score);for(const x of ranked){if(selected.some(y=>y.id===x.id))continue;if(selected.length>=7)break;if(x.score>0)selected.push(x)}if(selected.length<4){['tokyo','matsumoto','takayama','kanazawa','kyoto'].forEach(id=>{const x=pool.find(y=>y.id===id);if(x&&!selected.some(y=>y.id===id))selected.push(x)})}const order={east:1,alps:2,west:3,kyushu:4,hokkaido:5};selected=selected.slice(0,8).sort((a,b)=>order[a.area]-order[b.area]);let remain=p.days;selected.forEach(x=>{x.use=x.id==='tokyo'?Math.min(x.n,p.tokyoMax):x.n;remain-=x.use});let i=0;while(remain>0&&selected.length){selected[i%selected.length].use++;remain--;i++}while(remain<0&&selected.length>2){const x=selected.slice().reverse().find(x=>x.use>1);if(x){x.use--;remain++}else{selected.pop();remain++}}return selected}
function leg(a,b){const direct=legs[`${a.en}|${b.en}`]||legs[`${b.en}|${a.en}`];if(direct)return direct;return['Train / bus / flight depending on segment','проверьте перед бронированием','цена зависит от даты и тарифа']}
function applyFilters(p){const monthSel=document.querySelector('.filters select');if(monthSel&&p.month){monthSel.value=String(p.month);monthSel.dispatchEvent(new Event('change',{bubbles:true}))}const boxes=[...document.querySelectorAll('.mi-option input[type=checkbox]')];if(boxes.length&&p.tags.length){boxes.forEach(b=>{const lab=b.closest('label')?.textContent?.toLowerCase()||'';const wanted=p.tags.some(t=>({mountains:['горы','mountains'],onsen:['онсэн','onsen'],sea:['море','sea'],culture:['культура','culture'],food:['еда','food'],city:['города','cities'],unusual:['необычная','unusual'],nature:['природа','nature']}[t]||[]).some(w=>lab.includes(w)));if(b.checked!==wanted)b.click()})}}
function render(q){const p=parse(q),r=recommend(p);applyFilters(p);const out=document.querySelector('#kando-smart-result');let html=`<div class="ks-summary"><b>${p.days} дней${p.month?' · месяц '+p.month:''}</b><span>${p.tags.length?'Учёл: '+p.tags.join(', '):'Маршрут подобран по длительности и географии'}</span></div><div class="ks-route">`;let day=1,totalMin=0;for(let i=0;i<r.length;i++){const x=r[i];html+=`<div class="ks-stop"><div class="ks-day">Дни ${day}${x.use>1?'–'+(day+x.use-1):''}</div><div><b>${x.ru}</b><small>${x.use} ${x.use===1?'день':'дн.'}</small></div></div>`;day+=x.use;if(i<r.length-1){const l=leg(x,r[i+1]);html+=`<div class="ks-leg"><span>↓ ${l[0]}</span><span>⏱ ${l[1]} &nbsp; 💴 ${l[2]}</span></div>`}}html+='</div><p class="ks-note">Время и цены ориентировочные. Перед покупкой билетов проверьте конкретную дату и рейс.</p>';out.innerHTML=html;out.style.display='block'}
function mount(){if(document.querySelector('#kando-smart'))return;const root=document.querySelector('#root');if(!root||!root.children.length)return;const box=document.createElement('section');box.id='kando-smart';box.innerHTML=`<div class="ks-title"><b>Опиши свою Японию</b><span>Напиши обычным текстом, какой должна быть поездка</span></div><textarea id="kando-smart-input" placeholder="Например: 12 дней, апрель, первый раз в Японии, люблю горы, маленькие города и онсэны. Токио максимум 3 дня."></textarea><button id="kando-smart-go">Предложить маршрут</button><div class="ks-examples">Можно написать: «3 дня в Токио + 3 дня в горах + 5 дней на море»</div><div id="kando-smart-result"></div>`;root.insertBefore(box,root.querySelector('nav')?.nextSibling||root.firstChild);document.querySelector('#kando-smart-go').onclick=()=>{const q=document.querySelector('#kando-smart-input').value.trim();if(q)render(q)};document.querySelector('#kando-smart-input').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')document.querySelector('#kando-smart-go').click()})}
new MutationObserver(mount).observe(document.documentElement,{childList:true,subtree:true});mount()})();